language: node_js
node_js:
  - "6"
  - "node"
services:
  - docker
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - npm i npm@^4 -g
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm run build:prod
  - npm run ci
cache:
  directories:
    - node_modules
sudo: required
